internal partial class Program
{
    class City
    {
        public static List<string> Cities = new()
        {
      "Ol’ginka",
      "Fucun",
      "Kremenki",
      "Kuangshan",
      "Malainen Luma",
      "Bluefields",
      "Nanyang",
      "Zarzal",
      "Imeni Babushkina",
      "Kilmacanoge",
      "Harstad",
      "Hostomice",
      "Haarlem",
      "El Carmen",
      "Lille",
      "Khulm",
      "Avdzaga",
      "Nove-Misto",
      "Trelew",
      "Kemil",
      "Dek’emhāre",
      "Malinao",
      "Pasar Kidul",
      "Gaotuan",
      "Lypnyazhka",
      "Nogent-sur-Marne",
      "Aoufous",
      "Liaoyang",
      "Portela",
      "Raoshi",
      "Kudang",
      "Dolores",
      "Batan",
      "Butwāl",
      "Beberibe",
      "Abade de Neiva",
      "Ibusuki",
      "Skellefteå",
      "Guanban",
      "Dazhan",
      "Faro",
      "Ivanovka",
      "Don Carlos",
      "Qorovulbozor Shahri",
      "Åmål",
      "Sosnovka",
      "Chợ Mới",
      "Tha Mai",
      "Krajan Jabungcandi",
      "Wróblew",
      "Prigrevica",
      "Aitape",
      "Kombolcha",
      "Gines-Patay",
      "Tanjung",
      "Koygorodok",
      "Puerto Esperanza",
      "Pu’an",
      "Chai Nat",
      "Krousón",
      "Oldřišov",
      "Gandong",
      "Fengshou",
      "Bancroft",
      "Ilama",
      "Postmasburg",
      "Xihe",
      "Kalávryta",
      "Dededo Village",
      "Bacacay",
      "Teresita",
      "Xinwan",
      "Karanglo",
      "Créteil",
      "Sikka",
      "Ntoum",
      "Siyang",
      "Waitun",
      "Vishnyeva",
      "Betulia",
      "Kladi",
      "Ngembo",
      "Ngama",
      "Lucun",
      "Lodja",
      "Farnham",
      "Vizal San Pablo",
      "Diên Khánh",
      "Madīnat ash Shamāl",
      "Artashat",
      "Yeosu",
      "Yur’yev-Pol’skiy",
      "Koz’modem’yansk",
      "Vyazniki",
      "Longquan",
      "Shengli",
      "Yuanqian",
      "Nedakonice",
      "Sindi",
      "Serawai"
    };

    }
}